[general]
# Reload config automatically on save
live_config_reload = true

# to install the themes
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

# Import theme
import = [
  "~/.config/alacritty/themes/themes/vague.toml"
]

# -------------------------------------------------------------------
# Fonts
# -------------------------------------------------------------------
[font]
# Font size in pts
size = 12.0

# Normal font
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Bold font
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

# Italic font
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

# Bold Italic font
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

# -------------------------------------------------------------------
# Cursor
# -------------------------------------------------------------------
[cursor]
# Cursor shape + blinking together (object)
style = { shape = "Block", blinking = "Always" }

# Blink interval in ms (lower = faster)
blink_interval = 750

# Time after which the cursor stops blinking (0 = never stops)
blink_timeout = 0

# Make the cursor hollow when the window is not focused
unfocused_hollow = true

# Cursor thickness relative to the cell (0.0â€“1.0)
thickness = 0.20

# -------------------------------------------------------------------
# Scrolling
# -------------------------------------------------------------------
[scrolling]
history = 10000
multiplier = 3

# -------------------------------------------------------------------
# Selection
# -------------------------------------------------------------------
[selection]
save_to_clipboard = true

# -------------------------------------------------------------------
# Terminal Environment
# -------------------------------------------------------------------
[env]
TERM = "xterm-256color"

# -------------------------------------------------------------------
# Window / Appearance
# -------------------------------------------------------------------
[window]
dynamic_padding = true
decorations = "full"    # border + title bar
opacity = 1.00

# Inner padding (space around content)
padding = { x = 6, y = 6 }
